export const likeOptions = [
    "Spontaneous detours",
    "Well-organized trips",
    "Meeting new people",
    "Physical challenges",
    "Historical sites",
    "Detailed itineraries",
    "Group activities",
    "Adrenaline rushes",
    "Cultural immersion",
    "Predictability",
    "Social gatherings",
    "Conquering difficult terrain",
    "Learning local traditions",
    "Checking off plans",
    "Making new friends",
    "Testing personal limits",
    "Quiet reflection",
]

export const dislikeOptions = [
    "Rigid schedules",
    "Last-minute changes",
    "Large crowds",
    "Comfort-focused travel",
    "Touristy attractions",
    "Disorganization",
    "Isolation",
    "Slow-paced activities",
    "Superficial experiences",
    "Unpredictability",
    "Limited social interaction",
    "Safety constraints",
    "Rushed cultural visits",
    "Deviations from plans",
    "Quiet environments",
    "Easy, unchallenging paths",
    "Structured tours",
]

export const destinationOptions = [
    "Remote mountains",
    "Well-developed cities",
    "Vibrant beach towns",
    "Challenging wilderness",
    "Historic cultural centers",
    "Organized tourist destinations",
    "Social hotspots",
    "Extreme environments",
    "Ancient villages",
    "Switzerland",
    "Japan",
    "Bali",
    "New Zealand",
    "Italy",
    "Thailand",
    "Norway",
    "Peru",
]

export const paceOptions = ["fast", "planned", "slow", "spontaneous"]